### PR TITLE
$.every('minute', function() { … })

### PR DESCRIPTION
**Pull request by ai**
More nicw syntax sugar and human words. In normal world we say “check every second”, not “check every 1 second”. So it will be more nice to have syntax like:

```
$.every('minute', function() { … })
```

I add test for it and add sample in README and code docs. But I didn’t know, how update `.min.js` version and `doc/`.

### CODE REVIEW

**Comment by kossnocorp** [comment]
+1! Awesome addition!

**Comment by avk** [comment]
Thanks, will check it out shortly and add some instructions for how to contribute (esp. updating `.min.js` and `doc/`).

**Comment by avk** [comment]
[Merged](https://github.com/avk/jQuery-Chrono/compare/3b123b97028abf07a4fc...dccb83bb283f3d0a2b2a) into master.

**Comment by avk** [comment]
Also updated the README with how to contribute. Thanks for your addition!

**Pull request closed without merging**
