### PR TITLE
Adding support for multidimensional arrays so user can say 1 minute, 30 seconds

### PR DESCRIPTION
**Pull request by janhartigan**
I'm sure we could go even further to allow comma-separated strings like: '1 minute, 32 seconds'.

Sorry if there are multiple changes showing up in my request. I originally forked this project from ChiperSoft who originally forked it from you

https://github.com/ChiperSoft/Timed

However, I made a secondary repo by forking it from you, and the only changes I made can be seen in this commit here:

https://github.com/janhartigan/jQuery-Chrono/commit/09b7908b6c73652277bcdd37099eba5c1ea5e6cd

In this pull request screen, GitHub says I made 1 commit and changed 2 files, but when I click on those tabs, it shows all the commits made by ChiperSoft and by me on ChiperSoft's changes. Seems to be a weird bug.

### CODE REVIEW

**Comment by avk** [comment]
Hi, thanks for contributing. "1 minute, 32 seconds" does seem intuitive but I'm not so sure about ["1", "minute"]. 

I'm a bit confused by the new syntax in the README:

```
    $.after([
        ["1", "minute"],
        [34, "seconds"],
        [100, "milliseconds"]
    ], function() { ... });
```

Does that mean the timer will be run at all of those intervals?

**Comment by janhartigan** [comment]
Hey no problem. That syntax means it will be run once at 1 minute, 34 seconds, 100 milliseconds after it's called. I thought it was a decent way to add times together because I didn't see that functionality in your original code.

**Comment by avk** [comment]
Oh, I see. I thought you wanted to execute the code at 3 different intervals. I think one string argument would be much more natural: <code>"1 minute, 34 seconds, 100 milliseconds"</code>.

Do you find yourself needing this type of specificity often? I can't think of a time when I needed such a precise timer.

**Comment by janhartigan** [comment]
To be honest, it's the first thing I thought of when I saw your plugin. It seems reasonable that someone would want to have something go every 1 minute and 30 seconds instead of every 1 minute. If you give me a little time to sort it out, I could get that comma-string working and remove the array code :-)

**Comment by avk** [comment]
Sure, happy to see the string code. But if you want me to merge it, please: 
- fork it from [my latest commit](https://github.com/avk/jQuery-Chrono/commit/972f2aaed1aa8ae5cfe2faad1cfd8931b913eb62), not ChiperSoft's repo
- keep the changes to a minimum: your current pull request has a lot of whitespace but not semantic changes
- provide the relevant QUnit unit tests and make sure all existing tests pass (in **test/tests.js**)
- regenerate **jquery.chrono.min.js**
- regenerate **doc/** with **jsdoc-toolkit/**

I'll add these steps to a new Contributing section of the **README** when I get a chance. 

Thanks and let me know if you need help with anything!

**Pull request closed without merging**
