### PR TITLE
Adding ability to have comma-separated string like '1 minute, 2 seconds'

### PR DESCRIPTION
**Pull request by janhartigan**
I also added a $.trim() in there to be sure that you can write '1 minute' instead of just '1minute'. I'm pretty sure I did everything else right...jsdoctoolkit was autogenerated, I used yui compressor to min the jquery.chrono.js file...

There's just one thing I noticed while running the unit tests. The last test was intermittently failing, and I noticed it was down to how much time in milliseconds was elapsing on my cpu (i.e. the timers were unsurprisingly not syncing). I came up with a solution to this, if you're interested, and will issue a separate pull request for that other commit.

### CODE REVIEW

**Comment by janhartigan** [comment]
Here's that other commit that I mentioned:

https://github.com/janhartigan/jQuery-Chrono/commit/fdc6311d9d6e5e70a2e8b99b267b954511d641a6

Notice I also did a merge after this to include the milliseconds + 1 again...I didn't mean to take that out.

It's pretty small, so you may just want to change it in your code base. This doesn't fail as often, though I'm not entirely sure what's going on. I initially made that extra setTimeout into a function that is called inside the .every(), but then I realized that that would be a poor test. So I just fiddled around with the amount of time given to the test.

**Comment by avk** [comment]
Sorry, took me a while to get around to reviewing this. Nice job.

I've pulled it into the [comma-separated-delays branch](https://github.com/avk/jQuery-Chrono/tree/comma-separated-delays) and expanded on your work a bit (more tests, a little refactoring). Thoughts? If you're okay with it, I'll merge that into master.

**Comment by avk** [comment]
Have you had a chance to look at my branch? I'll merge it in soon if there are no objections.

**Comment by janhartigan** [comment]
Hey avk sorry! Yes your updates look good and those tests are more extensive than what I had. I like it! I say merge the branches.

Thanks again for this project...random ideas like yours help spur my creativity :-)

**Comment by avk** [comment]
Thanks for the kind words!

Merged into master and released as version 1.1 :)

**Pull request closed without merging**
